# Generated by Django 5.0.2 on 2024-02-17 17:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('Отели', 'Отели'), ('Рестораны', 'Рестораны'), ('Спа-салоны', 'Спа-салоны')], default=None, max_length=255, verbose_name='Категория статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(blank=True, choices=[('Отели', 'Отели'), ('Рестораны', 'Рестораны'), ('Спа-салоны', 'Спа-салоны')], default=None, max_length=255, null=True, verbose_name='Категория статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Отели', 'Отели'), ('Рестораны', 'Рестораны'), ('Спа-салоны', 'Спа-салоны')], default=None, max_length=255, verbose_name='Категория статьи')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Раскошный отдых',
                'verbose_name_plural': 'Раскошный отдых',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('Недвижимость', 'Недвижимость'), ('Раскошный отдых', 'Раскошный отдых'), ('Продукты', 'Продукты'), ('Интервью', 'Интервью')], max_length=255, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': ('Популярные',),
                'verbose_name_plural': 'Популярные',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='DesignDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('Отели', 'Отели'), ('Рестораны', 'Рестораны'), ('Спа-салоны', 'Спа-салоны')], default=None, max_length=255, verbose_name='Категория статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design', to='main.design')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='EstateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('Отели', 'Отели'), ('Рестораны', 'Рестораны'), ('Спа-салоны', 'Спа-салоны')], default=None, max_length=255, verbose_name='Категория статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='main.estate')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='HolidayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Отели', 'Отели'), ('Рестораны', 'Рестораны'), ('Спа-салоны', 'Спа-салоны')], default=None, max_length=255, verbose_name='Категория статьи')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to='main.holiday')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='main.interview')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='PopularDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('Недвижимость', 'Недвижимость'), ('Раскошный отдых', 'Раскошный отдых'), ('Продукты', 'Продукты'), ('Интервью', 'Интервью')], max_length=255, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='main.popular')),
            ],
            options={
                'verbose_name': ('Дополнительно',),
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.product')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
    ]
