# Generated by Django 4.2.7 on 2024-02-29 14:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Заголовка',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('lang', models.CharField(blank=True, choices=[('Кыргыз тили', 'Кыргыз тили'), ('Русский язык', 'Русский язык')], max_length=2555, null=True, verbose_name='Язык')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя модификация')),
                ('save_state', models.BooleanField(default=False, verbose_name='Сохранить')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='main.category', verbose_name='категория')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all', to='main.header', verbose_name='Заголовка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='SubHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегория')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='main.header')),
            ],
            options={
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=100, verbose_name='Подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='ResidentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='main.resident')),
            ],
            options={
                'verbose_name': 'Дополнительно',
                'verbose_name_plural': 'Дополнительно',
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
