# Generated by Django 5.0.2 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('description', models.TextField(verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('description', models.TextField(verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('description', models.TextField(verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Раскошный отдых',
                'verbose_name_plural': 'Раскошный отдых',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('description', models.TextField(verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(choices=[('Недвижимость', 'Недвижимость'), ('Раскошный отдых', 'Раскошный отдых'), ('Продукты', 'Продукты'), ('Интервью', 'Интервью')], max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('description', models.TextField(verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': ('Популярные',),
                'verbose_name_plural': 'Популярные',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата добавление')),
                ('description', models.TextField(verbose_name='Текст')),
                ('last_mod', models.DateTimeField(auto_now=True, verbose_name='Последняя мадификация')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
