# Generated by Django 4.2 on 2024-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, choices=[('Популярные', 'Популярные'), ('Недвижимость', 'Недвижимость'), ('Раскошный отдых', 'Раскошный отдых'), ('Интервью', 'Интервью'), ('Продукты', 'Продукты'), ('Предложение от компании', 'Предложение от компании'), ('Популярдуу', 'Популярдуу'), ('Кыймылсыз мулк', 'Кыймылсыз мулк')], max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
    ]
