# Generated by Django 4.2 on 2024-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='language',
            field=models.CharField(blank=True, choices=[('kg', 'Кыргыз тили'), ('ru', 'Русский язык')], default='ru', max_length=255, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='slider',
            name='language',
            field=models.CharField(blank=True, choices=[('kg', 'Кыргыз тили'), ('ru', 'Русский язык')], default='ru', max_length=255, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='subheader',
            name='language',
            field=models.CharField(blank=True, choices=[('kg', 'Кыргыз тили'), ('ru', 'Русский язык')], default='ru', max_length=255, null=True, verbose_name='Язык'),
        ),
    ]
