# Generated by Django 5.0.2 on 2024-02-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='name',
        ),
    ]
