# Generated by Django 4.2 on 2024-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resident_language_slider_language_subheader_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentdetail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
