# Generated by Django 4.2 on 2024-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('kg', 'Кыргыз тили'), ('ru', 'Русский язык')], default='ru', max_length=255, null=True, verbose_name='Язык')),
                ('blog', models.CharField(choices=[('Главное', 'Главное'), ('Популярные', 'Популярные'), ('Недвижимость', 'Недвижимость'), ('Раскошный отдых', 'Раскошный отдых'), ('Продукты', 'Продукты'), ('Интервью', 'Интервью'), ('Предложение от компании', 'Предложение от компании'), ('Башкы', 'Башкы'), ('Маектешуу', 'Маектешуу'), ('Компаниядан сунуштар', 'Компаниядан сунуштар'), ('Люкс майрам', 'Люкс майрам'), ('Кыймылсыз мулк', 'Кыймылсыз мулк'), ('Популярдуу', 'Популярдуу'), ('Продукттар', 'Продукттар')], max_length=255, verbose_name='Блог')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Баннер для ПК Версии')),
                ('img', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Баннер для Моб Версии')),
                ('date', models.DateField(verbose_name='Дата истечение')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Банер',
            },
        ),
    ]
