# Generated by Django 5.0.2 on 2024-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_design_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='description',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='description',
        ),
        migrations.RemoveField(
            model_name='popular',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория статьи'),
        ),
    ]
