# Generated by Django 4.2 on 2024-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='last',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
    ]
