# Generated by Django 4.2 on 2024-08-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='img',
            new_name='mb_img',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='pc_image',
        ),
    ]
