# Generated by Django 4.2 on 2024-03-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_last_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last',
            field=models.ForeignKey(blank=True, limit_choices_to={'language': 'ru'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Выберите русскую версию категории!'),
        ),
    ]
