# Generated by Django 4.2 on 2024-03-05 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_residentdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentdetail',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
