# Generated by Django 4.2 on 2024-08-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_img_banner_mb_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
