# Generated by Django 4.2 on 2024-03-06 07:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_residentdetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
