# Generated by Django 4.2.7 on 2024-03-11 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor.fields.RichTextField(verbose_name='Комментарии'),
        ),
    ]
