# Generated by Django 4.2 on 2024-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='ratation',
            field=models.CharField(choices=[('Ратация 1', 'Ратация 1'), ('Ратация 2', 'Ратация 2'), ('Ратация 3', 'Ратация 3'), ('Ратация 4', 'Ратация 4'), ('Ратация 5', 'Ратация 5')], default=1, max_length=255, verbose_name='Ратация'),
            preserve_default=False,
        ),
    ]
