# Generated by Django 4.2 on 2024-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_banner_ratation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.UniqueConstraint(fields=('blog', 'ratation'), name='unique_blog_ratation'),
        ),
    ]
