# Generated by Django 4.2 on 2024-03-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_subcategory_options_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='last',
        ),
    ]
