# Generated by Django 4.2 on 2024-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_banner_unique_blog_ratation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '', 'verbose_name_plural': 'Баннер'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='ratation',
            field=models.CharField(choices=[('Ротация 1', 'Ротация 1'), ('Ротация 2', 'Ротация 2'), ('Ротация 3', 'Ротация 3'), ('Ротация 4', 'Ротация 4'), ('Ротация 5', 'Ротация 5')], max_length=255, verbose_name='Рoтация'),
        ),
    ]
