# Generated by Django 4.2 on 2024-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_banner_options_alter_banner_ratation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='ratation',
            field=models.CharField(choices=[('1', 'Ротация 1'), ('2', 'Ротация 2'), ('3', 'Ротация 3'), ('4', 'Ротация 4'), ('5', 'Ротация 5')], max_length=255, verbose_name='Рoтация'),
        ),
    ]
