# Generated by Django 4.2 on 2024-03-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_slider_last'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
