# Generated by Django 4.2 on 2024-03-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_subcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
