# Generated by Django 4.2 on 2024-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='Выберите русскую версию статьи выше, чтобы добавить изображение автоматически!', null=True, upload_to='post/%Y_%m/', verbose_name='Изображение'),
        ),
    ]
