# Generated by Django 4.2.7 on 2024-03-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_post_last_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_comment',
        ),
    ]
