# Generated by Django 4.2.7 on 2024-03-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_user_comments_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_comment',
            new_name='user',
        ),
    ]
