# Generated by Django 4.2 on 2024-03-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_slider_url_alter_postfile_file_alter_slider_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': '', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y_%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='exception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception', to='main.post'),
        ),
    ]
