# Generated by Django 4.2.7 on 2024-02-29 12:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изоброжение')),
                ('last_mood', models.DateField(blank=True, null=True, verbose_name='Последняя модификация')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Text')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изоброжение')),
                ('last_mood', models.DateField(blank=True, null=True, verbose_name='Последняя модификация')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='home.about')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
