# Generated by Django 5.0.2 on 2024-02-17 17:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изоброжение')),
                ('last_mood', models.DateField(blank=True, null=True, verbose_name='Последняя модификация')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изоброжение')),
                ('last_mood', models.DateField(blank=True, null=True, verbose_name='Последняя модификация')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='home.about')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
