# Generated by Django 5.0.2 on 2024-02-17 17:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_aboutdetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdetail',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
