# Generated by Django 5.0.2 on 2024-02-20 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aboutdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdetail',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Text'),
        ),
    ]
